### ISSUE TITLE
text wrap is a bit wonky

### ISSUE THREAD

**Issue by danlbob** [crobi/dnd5e-quickref#3]
On my phone when it collapses to 2 column view, some of the description text wraps down and collides with the text/icon below
screenshot https://www.dropbox.com/s/hn2au1u3kxuukjv/2015-01-22%2020.56.50.png?dl=0

**Comment by crobi** [comment]
What phone is that? If your screen resolution is under a certain threshold the layout collapses to a 1 column view, but the threshold is probably too low. It's supposed to show a 1 column view on most smart phones in portrait mode.

**Comment by SecretOnline** [comment]
Removing the height in `.itemsize` allows the boxes to take as much space as they need. (Image below) Perhaps a `minimum-height: ???px;` would be useful.

![2015-01-23_10-05-04](https://cloud.githubusercontent.com/assets/7552536/5864531/9586cbfc-a2e7-11e4-99e4-e28800367855.png)

This does have the minor disadvantage of the page looking a little bit messy with the different sizes of boxes. For example, further up.

![2015-01-23_10-09-27](https://cloud.githubusercontent.com/assets/7552536/5864596/2730290e-a2e8-11e4-892d-dd091289fe3b.png)

**Comment by danlbob** [comment]
Its a nexus 6 hot off the shelf.

**Comment by crobi** [comment]
Another alternative to switching to a 1 column view is to limit the subtitle to one line, e.g., via styling the `<span>` with

```
display: block;
max-height: 16pt;
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

Thinking about it, the title and subtitle should be `<div>`s anyway and not two `<span>`s with a `<br/>` in between

**Comment by danlbob** [comment]
you might also just nudge out that media query to include a few more pixels...
http://mydevice.io/devices/

Looks like my css width is 412px and the media query breaks at 400px;

**Comment by SecretOnline** [comment]
The only disadvantage with this is the hidden overflow. 

![2015-01-23_10-32-00](https://cloud.githubusercontent.com/assets/7552536/5865012/4acfbd72-a2eb-11e4-974c-e10c5d1c4768.png)

I took that screenshot almost right on the breakpoint, to see the absolute worst it could be at. (If it seems like I'm trying to poke holes in everything, it's because I am. Sorry)

The layout is consistent, which is nicer to look at. Certain subtitles have been cut short, and the title for "Use class feature" has been cut too.

**Comment by crobi** [comment]
Which one would you prefer? A 1 column layout or clipped text? I am thinking about setting the minimum width for a 2 column layout to 480px and then using `text-overflow: ellipsis;` to indicate that text has been clipped.

**Comment by danlbob** [comment]
1 column would be fine. I think ellipses are only good if you can somehow see the rest of the content. maybe put the title/description in the modal window as well?

**Comment by SecretOnline** [comment]
I'd go with your suggestion too, @crobi. 

@danlbob, currently the title is seen, and the subtitle in the modal is a longer version of the item subtitle. Of course, that *can* be changed with the data files, but by default you don't need to worry about that.

**Comment by crobi** [comment]
@SecretOnline yes, that's exactly the idea. The `description` is just a longer form of the `subtitle` property. Might have called it `subtitle_long` instead of `description`.

I think having a consistent layout is more important than clipped text. To see the details, you open the modal anyway, and nothing is clipped in the modal.

The minimum width for two columns is now 480px, and the text of both the title and the subtitle is clipped, with ellipses indicating that it has been clipped. According to http://mydevice.io/devices/, all smartphones and phablets (what the hell is that name) will now display 1 column in portrait and 2 columns in landscape mode. Tablets will display 2-3 columns in portrait and 3-4 columns in landscape mode, depending on the model.

Some smartphones will show moderate clipping in landscape mode, and some tablets will show minor clipping in portrait mode. This is good enough for now, since people can edit the data files and we cannot know how long their subtitles will be anyway.

**Comment by danlbob** [comment]
Looks good. Thank you!
